import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const html=read('public/index.html');
const app=read('public/app.js');
const manifest=JSON.parse(read('public/manifest.webmanifest'));
const doc=read('KAIROS_REBRAND.md');
assert.match(html,/<title>KAIROS Paper Broker<\/title>/);
assert.match(html,/\/kairos-mark\.png\?v=7\.3\.0/);
assert.match(html,/\/favicon-64\.png\?v=7\.3\.0/);
assert.equal(manifest.name,'KAIROS Paper Broker');
assert.equal(manifest.short_name,'KAIROS');
assert.ok(manifest.icons.some(x=>x.src.includes('kairos-icon-192.png')));
assert.ok(manifest.icons.some(x=>x.src.includes('kairos-icon-512.png')));
for(const f of ['public/kairos-mark.png','public/favicon-64.png','public/kairos-icon-192.png','public/kairos-icon-512.png','public/apple-touch-icon.png']) assert.ok(fs.statSync(f).size>1000,`${f} missing/too small`);
assert.doesNotMatch(app,/PANTHEON OF WEALTH|TRACE LAB|EVOLUTION LAB/);
assert.match(app,/Decision Review/);
assert.match(app,/Learning Lab/);
assert.match(app,/Decision History/);
assert.match(app,/SPY benchmark/);
assert.doesNotMatch(app,/S&P benchmark/);
assert.match(doc,/HADES_\*.*SAURON_\*/s);
assert.match(doc,/official customer-facing mark/i);
console.log(JSON.stringify({ok:true,rebrand:'KAIROS V7.3'},null,2));
