import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const html=read('public/index.html');
const app=read('public/app.js');
const health=read('netlify/functions/provider-health.mjs');
const migration=read('MIGRATION_NETLIFY_AI_GATEWAY.md');
assert.match(html,/V7\.3 · DECISION INTELLIGENCE/);
assert.match(html,/id="toast"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(html,/id="chatMessages"[^>]*aria-live="polite"/);
assert.match(html,/id="advisorCloseBtn"[^>]*aria-label=/);
assert.match(html,/id="systemCloseBtn"[^>]*aria-label=/);
assert.match(html,/id="userAvatar"[^>]*role="button"[^>]*tabindex="0"/);
assert.match(app,/meta\.textContent=`DECISION JOURNAL · V7\.3 ·/);
assert.doesNotMatch(app,/meta\.textContent=`V7\.2 ·/);
assert.match(app,/Manual display price/);
assert.match(app,/never qualify as verified automatic-execution or Decision Review evidence/);
assert.doesNotMatch(app,/Refresh market intelligence/);
assert.match(app,/aria-busy/);
assert.match(app,/e\.key!==['"]Escape['"]/);
assert.match(health,/KAIROS V7\.3 uses Netlify AI Gateway/);
assert.match(migration,/KAIROS V7\.3/);
console.log(JSON.stringify({ok:true,polish:'v7.3 release polish'},null,2));
